Original Structures::Structures::WriteStructureTemplate
float Original Structures::Structures::WriteStructureTemplate.VERSION
tuple Original Structures::Structures::WriteStructureTemplate::base_path
string Original Structures::Structures::WriteStructureTemplate.structures_lookup_file_name
Original Structures::Structures::WriteStructureTemplate.structures_file_path
tuple Original Structures::Structures::WriteStructureTemplate.structures_lookup
list Original Structures::Structures::WriteStructureTemplate.templates_list
tuple Original Structures::Structures::WriteStructureTemplate.structure_data
string Original Structures::Structures::WriteStructureTemplate.structures_file_name
def Original Structures.Structures.WriteStructureTemplate.define_template_attributes
Create a dictionary with Type Variable values that define all of the template attributes.
Referenced by Original Structures.Structures.WriteStructureTemplate.build_template_data.
def Original Structures.Structures.WriteStructureTemplate.define_template_tables
References Original Structures.Structures.StructureData.define_structure_attributes.
Referenced by Original Structures.Structures.WriteStructureTemplate.build_templates.
def Original Structures.Structures.WriteStructureTemplate.build_template_data
References Original Structures.Structures.WriteStructureTemplate.define_template_attributes.
Referenced by Original Structures.Structures.WriteStructureTemplate.build_templates.
def Original Structures.Structures.WriteStructureTemplate.list_of_structures
Assemble a text string that includes the begin_text (or default) and a comma separated list of all structure IDs in the structures DataFrame The structures are sorted alphabetically by default.
Referenced by Original Structures.Structures.WriteStructureTemplate.build_templates.
def Original Structures.Structures.WriteStructureTemplate.add_preview
Add a the preview element to the template tree using the data in template_data.
Referenced by Original Structures.Structures.WriteStructureTemplate.make_template.
def Original Structures.Structures.WriteStructureTemplate.make_template
References Original Structures.Structures.WriteStructureTemplate.add_preview, Original Structures.Structures.StructureData.build_structures_element.
Referenced by Original Structures.Structures.WriteStructureTemplate.build_templates.
def Original Structures.Structures.WriteStructureTemplate.build_templates
Build a collection of structure template files from the list of templates in template_list that describe template data in the template file. Structure data used for the templates comes from the structures_lookup data-frame.
References Original Structures.Structures.StructureData.build_structures_list, Original Structures.Structures.WriteStructureTemplate.build_template_data, Original Structures.Structures.WriteStructureTemplate.define_template_tables, Original Structures.Structures.WriteStructureTemplate.list_of_structures, Original Structures.Structures.WriteStructureTemplate.make_template.
Referenced by Original Structures.Structures.SelectTemplates.main.