Original Structures::Structures::SelectTemplates
string Original Structures::Structures::SelectTemplates.TEMPLATE_LIST_FILE
def Original Structures.Structures.SelectTemplates.define_template_list
Create a dictionary with Type Variable values that define the template list columns.
Referenced by Original Structures.Structures.SelectTemplates.import_template_list.
def Original Structures.Structures.SelectTemplates.import_template_list
References Original Structures.Structures.SelectTemplates.define_template_list.
Referenced by Original Structures.Structures.SelectTemplates.select_templates.
def Original Structures.Structures.SelectTemplates.select_templates
References Original Structures.Structures.SelectTemplates.import_template_list.
Referenced by Original Structures.Structures.SelectTemplates.main.
def Original Structures.Structures.SelectTemplates.main
References Original Structures.Structures.StructureData.build_structures_lookup, Original Structures.Structures.WriteStructureTemplate.build_templates, Original Structures.Structures.SelectTemplates.select_templates.