Original Structures::Structures::StructureData
tuple Original Structures::Structures::StructureData.structures_file_path
tuple Original Structures::Structures::StructureData.structures_lookup
tuple Original Structures::Structures::StructureData.file_path
string Original Structures::Structures::StructureData.sheet_name
string Original Structures::Structures::StructureData.title
string Original Structures::Structures::StructureData.offset
string Original Structures::Structures::StructureData.index
int Original Structures::Structures::StructureData.columns
tuple Original Structures::Structures::StructureData.structures_table
tuple Original Structures::Structures::StructureData.structures
tuple Original Structures::Structures::StructureData.structure_set
def Original Structures.Structures.StructureData.define_structure_attributes
Create a dictionary with Type Variable values that define all of the structure attributes. The attributes: EUDAlpha TCPAlpha TCPBeta and TCPGamma Are supplied but not used, the add_structure method forces them to be: 'xsi:nil="true"'
Referenced by Original Structures.Structures.StructureData.build_structures_lookup, Original Structures.Structures.WriteStructureTemplate.define_template_tables.
def Original Structures.Structures.StructureData.define_structure_tables
Referenced by Original Structures.Structures.StructureData.build_structures_lookup.
def Original Structures.Structures.StructureData.build_structures_lookup
References Original Structures.Structures.StructureData.define_structure_attributes, Original Structures.Structures.StructureData.define_structure_tables.
Referenced by Original Structures.Structures.SelectTemplates.main.
def Original Structures.Structures.StructureData.build_structures_list
Read in a list of structures and attributes. Merge this with structures_lookup to generate a new DataFrame containing only the selected structures.
Referenced by Original Structures.Structures.WriteStructureTemplate.build_templates.
def Original Structures.Structures.StructureData.build_structures_element
Build an XML structures element with SubElements from the structures DataFrame using the structure data in structures_lookup.
References Original Structures.Structures.StructureData.add_structure.
Referenced by Original Structures.Structures.WriteStructureTemplate.make_template.
def Original Structures.Structures.StructureData.add_structure
Add a new structure to the template tree using the data in structure_data. The order of the elements is important The attributes: EUDAlpha TCPAlpha TCPBeta and TCPGamma Are forced to be: 'xsi:nil="true"'
Referenced by Original Structures.Structures.StructureData.build_structures_element.