Original Structures::Structures::Tables
Original Structures::Structures::Tables.always_true
list Original Structures::Structures::Tables.VARIABLE_TYPES
string Original Structures::Structures::Tables.DEFAULT_INDEX
tuple Original Structures::Structures::Tables.file_path
string Original Structures::Structures::Tables.sheet_name
string Original Structures::Structures::Tables.title
string Original Structures::Structures::Tables.offset
string Original Structures::Structures::Tables.index
int Original Structures::Structures::Tables.columns
int Original Structures::Structures::Tables.rows
tuple Original Structures::Structures::Tables.new_table
tuple Original Structures::Structures::Tables.basic_table
tuple Original Structures::Structures::Tables.df
tuple Original Structures::Structures::Tables.a
def Original Structures.Structures.Tables.xl_to_xy
Referenced by Original Structures.Structures.Tables.Table.read_table.
def Original Structures.Structures.Tables.get_value
return the requested value from a dictionary or series, testing for undefined items. If the requested value is not found in either dictionary ValueError is raised.
def Original Structures.Structures.Tables.select_variables
Selects the variables found in table and checks that its values are valid Parameters table: Required, Type DataFrame variables: Required, Type dict, A dict of Variable definitions that may be found as columns in the table. Returns: A subset of table containing only the columns found in variables or None if no columns found. Raises InvalidAttribute
Referenced by Original Structures.Structures.Tables.merge_tables, Original Structures.Structures.TestTablesClass.TestTableImporting.test_select_multiple_variable.
def Original Structures.Structures.Tables.merge_tables
Reads in, validates and merges a list of tables Only variables in the variables dictionary are merged Parameters spreadsheet_file: Required, Type Path, The path to the spreadsheet file tables_list: Required, Type list, A list of the Table objects defining each required table Note: all tables should have the same index defined Other than the index variable, no other variable should occur in more than one table. variables_list: Optional, Type dict, A dict of the Variable objects defining each table variable Returns merged_table: A Pandas data-frame created by merging all excel tables read in Raises MissingSpreadsheet MissingTable InvalidAttribute
References Original Structures.Structures.Tables.select_variables.
Referenced by Original Structures.Structures.TestTablesClass.TestTableImporting.test_merge_tables_with_duplicate_variables, Original Structures.Structures.TestTablesClass.TestTableImporting.test_merge_tables_with_missing_and_extra_values, Original Structures.Structures.TestTablesClass.TestTableImporting.test_merge_tables_with_one_column_dropped.
def Original Structures.Structures.Tables.process_defaults
Referenced by Original Structures.Structures.TestTablesClass.TestTableImporting.test_process_defaults, Original Structures.Structures.TestTablesClass.TestTableImporting.test_process_no_defaults.
def Original Structures.Structures.Tables.insert_defaults
Referenced by Original Structures.Structures.TestTablesClass.TestTableImporting.test_update_missing_values.
def Original Structures.Structures.Tables.insert_missing_variables
Referenced by Original Structures.Structures.TestTablesClass.TestTableImporting.test_insert_missing_variables.